// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UpdateAuth0Profile struct {
	Nickname     *string                `json:"Nickname"`
	UserMetadata map[string]interface{} `json:"user_metadata"`
	Picture      *string                `json:"picture"`
}
